import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() };
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), displayName: text("display_name"), nativeLanguage: text("native_language").default("zh-CN"), ...timestamps }, (t) => [uniqueIndex("users_email_idx").on(t.email)]);
export const speakers = sqliteTable("speakers", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), label: text("label").notNull(), isUser: integer("is_user", { mode: "boolean" }).default(false), ...timestamps });
export const conversations = sqliteTable("conversations", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), title: text("title").notNull(), occurredAt: integer("occurred_at", { mode: "timestamp" }), sourceType: text("source_type", { enum: ["transcript", "audio"] }).notNull(), rawStatus: text("raw_status", { enum: ["active", "deleted"] }).default("active"), audioObjectKey: text("audio_object_key"), ...timestamps });
export const transcripts = sqliteTable("transcripts", { id: text("id").primaryKey(), conversationId: text("conversation_id").references(() => conversations.id, { onDelete: "cascade" }).notNull(), rawText: text("raw_text").notNull(), language: text("language").default("en"), version: integer("version").default(1), ...timestamps });
export const transcriptSegments = sqliteTable("transcript_segments", { id: text("id").primaryKey(), transcriptId: text("transcript_id").references(() => transcripts.id, { onDelete: "cascade" }).notNull(), speakerId: text("speaker_id").references(() => speakers.id), sequence: integer("sequence").notNull(), text: text("text").notNull(), startMs: integer("start_ms"), endMs: integer("end_ms"), confidence: real("confidence"), ...timestamps });
export const vocabularyCandidates = sqliteTable("vocabulary_candidates", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), segmentId: text("segment_id").references(() => transcriptSegments.id, { onDelete: "set null" }), term: text("term").notNull(), candidateType: text("candidate_type"), reason: text("reason"), confidence: real("confidence"), decision: text("decision", { enum: ["pending", "known", "learning", "dismissed"] }).default("pending"), ...timestamps });
export const vocabularyItems = sqliteTable("vocabulary_items", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), sourceSegmentId: text("source_segment_id").references(() => transcriptSegments.id, { onDelete: "set null" }), term: text("term").notNull(), simpleDefinition: text("simple_definition"), chineseExplanation: text("chinese_explanation"), pronunciation: text("pronunciation"), originalAnswer: text("original_answer"), correctExplanation: text("correct_explanation"), alternateExample: text("alternate_example"), status: text("status", { enum: ["unknown", "learning", "recognized", "understood", "listening_ready", "active", "mastered"] }).default("unknown"), ...timestamps });
export const vocabularyMastery = sqliteTable("vocabulary_mastery", { id: text("id").primaryKey(), vocabularyItemId: text("vocabulary_item_id").references(() => vocabularyItems.id, { onDelete: "cascade" }).notNull(), recognition: real("recognition").default(0), contextualUnderstanding: real("contextual_understanding").default(0), listening: real("listening").default(0), recall: real("recall").default(0), activeUse: real("active_use").default(0), pronunciation: real("pronunciation").default(0), confidence: real("confidence").default(0), ...timestamps });
export const vocabularyAttempts = sqliteTable("vocabulary_attempts", { id: text("id").primaryKey(), vocabularyItemId: text("vocabulary_item_id").references(() => vocabularyItems.id, { onDelete: "cascade" }).notNull(), promptType: text("prompt_type").notNull(), prompt: text("prompt"), response: text("response"), selfRating: text("self_rating"), evaluation: text("evaluation", { enum: ["correct", "partial", "incorrect", "unknown"] }), feedback: text("feedback"), attemptedAt: integer("attempted_at", { mode: "timestamp" }).notNull() });
export const speakingIssues = sqliteTable("speaking_issues", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), segmentId: text("segment_id").references(() => transcriptSegments.id, { onDelete: "set null" }), category: text("category").notNull(), subcategory: text("subcategory"), severity: integer("severity").notNull(), originalText: text("original_text"), intendedMeaning: text("intended_meaning"), perceivedMeaning: text("perceived_meaning"), clearerAlternative: text("clearer_alternative"), evidenceType: text("evidence_type", { enum: ["transcript", "audio"] }).notNull(), ...timestamps });
export const errorPatterns = sqliteTable("error_patterns", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), category: text("category").notNull(), title: text("title").notNull(), explanation: text("explanation"), frequency: integer("frequency").default(0), severity: integer("severity").notNull(), priorityScore: real("priority_score"), trend: text("trend"), trainingStatus: text("training_status"), ...timestamps });
export const pronunciationIssues = sqliteTable("pronunciation_issues", { id: text("id").primaryKey(), speakingIssueId: text("speaking_issue_id").references(() => speakingIssues.id, { onDelete: "cascade" }).notNull(), feature: text("feature").notNull(), target: text("target"), observed: text("observed"), startMs: integer("start_ms"), endMs: integer("end_ms"), confidence: real("confidence"), ...timestamps });
export const speakingAttempts = sqliteTable("speaking_attempts", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), speakingIssueId: text("speaking_issue_id").references(() => speakingIssues.id, { onDelete: "set null" }), transcript: text("transcript"), audioObjectKey: text("audio_object_key"), evaluation: text("evaluation"), score: real("score"), attemptedAt: integer("attempted_at", { mode: "timestamp" }).notNull() });
export const practiceSessions = sqliteTable("practice_sessions", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), mode: text("mode", { enum: ["listening", "speaking"] }).notNull(), startedAt: integer("started_at", { mode: "timestamp" }).notNull(), completedAt: integer("completed_at", { mode: "timestamp" }), durationSeconds: integer("duration_seconds") });
export const reviewSchedules = sqliteTable("review_schedules", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), itemType: text("item_type", { enum: ["vocabulary", "error_pattern"] }).notNull(), itemId: text("item_id").notNull(), dueAt: integer("due_at", { mode: "timestamp" }).notNull(), intervalDays: real("interval_days").default(1), ease: real("ease").default(2.5), repetitions: integer("repetitions").default(0), lastResult: text("last_result"), ...timestamps });
export const weeklyFocus = sqliteTable("weekly_focus", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), errorPatternId: text("error_pattern_id").references(() => errorPatterns.id, { onDelete: "cascade" }).notNull(), weekStart: integer("week_start", { mode: "timestamp" }).notNull(), rank: integer("rank").notNull(), rationale: text("rationale"), status: text("status").default("active"), ...timestamps });
